ALTER TABLE users ADD COLUMN dashboard_widgets VARCHAR(256) NOT NULL DEFAULT 'TOTAL_REALIZED,BEST_MONTH,BEST_DAY';
ALTER TABLE users ADD COLUMN tax_capital_gains_rate NUMERIC(5, 2) NOT NULL DEFAULT 50.00;
ALTER TABLE users ADD COLUMN tax_personal_rate NUMERIC(5, 2) NOT NULL DEFAULT 50.00;
